apiVersion: v1
kind: Pod
metadata:
  name: triton-llm-test
  namespace: ziliang-xp
spec:
  priorityClassName: ziliang-xp-high
  restartPolicy: Never
  tolerations:
  - key: gpu-type
    operator: Equal
    value: mi325x
    effect: NoSchedule
  - key: amd.com/gpu
    operator: Exists
    effect: NoSchedule
  containers:
  - name: test
    image: rocm/dev-ubuntu-22.04:6.2-complete
    command: ["sleep", "infinity"]
    resources:
      limits:
        amd.com/gpu: "1"